# Netlify Configuration File

# Site settings
[build]
  publish = "frontend"
  command = "echo 'No build command needed for static site'"

# Redirects and headers
[[redirects]]
  from = "/api/*"
  to = "https://pricewise-oman-api.onrender.com/api/:splat"
  status = 200
  force = true

# Environment variables
[build.environment]
  API_URL = "https://pricewise-oman-api.onrender.com/api"

# Cache settings
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=604800"
